#!/bin/bash
# JankyBorders stock example config: https://github.com/FelixKratz/JankyBorders
# Width is toggled at runtime by the AeroSpace fork (BordersSync):
# 0 on floating workspaces, 6.0 on tiling ones.
options=(
    style=round
    width=6.0
    hidpi=off
    active_color=0xffe2e2e3
    inactive_color=0xff414550
)

borders "${options[@]}"
