# One list of software, and Homebrew as the only thing that installs any of it.
#
# software.toml is the whole authoring surface. Everything else here is
# rendering, and what it renders is a cache: the Brewfile and the cask files
# live under $STATE, not in the repo, because with [brew] and [cask] spelled
# out there is nothing in them the manifest does not already say. software.toml
# is the lock — a version bump is a diff in the file you edited.
typeset -g MANIFEST="$ROOT/software.toml"
typeset -g BREWFILE="$STATE/Brewfile"
typeset -g TAPDIR="$STATE/tap"
typeset -g TAPNAME="mac-setup/local"

typeset -ga SW_TAP SW_BREW SW_CASK SW_DOWNLOAD SW_MANUAL
typeset -gA SW_ATTR
typeset -gi SW_LOADED=0

_sw_trim() {
    setopt localoptions extendedglob
    local s=$1
    s="${s##[[:space:]]##}"
    s="${s%%[[:space:]]##}"
    print -r -- "$s"
}

# A deliberately small subset: section headers, bare names, and key = "value".
# Anything TOML can express that this cannot is a feature the manifest does not
# have, which is the point.
software_load() {
    (( SW_LOADED )) && return 0
    SW_LOADED=1
    SW_TAP=(); SW_BREW=(); SW_CASK=(); SW_DOWNLOAD=(); SW_MANUAL=(); SW_ATTR=()
    [[ -f "$MANIFEST" ]] || return 0
    local line sect='' name='' key val
    while IFS= read -r line; do
        line=$(_sw_trim "${line%%$'\r'}")
        [[ -z "$line" || "$line" == '#'* ]] && continue
        if [[ "$line" == '['*']' ]]; then
            sect="${${line#\[}%\]}"
            name=''
            case "$sect" in
                download.*) name="${sect#download.}"; sect=download; SW_DOWNLOAD+=("$name") ;;
                manual.*)   name="${sect#manual.}";   sect=manual;   SW_MANUAL+=("$name") ;;
                tap|brew|cask) ;;
                *) die "software.toml: unknown section [$sect]" ;;
            esac
            continue
        fi
        if [[ "$line" == *=* && "$sect" == (download|manual) ]]; then
            key=$(_sw_trim "${line%%=*}")
            val=$(_sw_trim "${line#*=}")
            val="${val%\"}"; val="${val#\"}"
            SW_ATTR[$sect.$name.$key]="$val"
            continue
        fi
        line="${line%%[[:space:]]#*}"
        case "$sect" in
            tap)  SW_TAP+=("$line") ;;
            brew) SW_BREW+=("$line") ;;
            cask) SW_CASK+=("$line") ;;
            '')   die "software.toml: '$line' is outside any section" ;;
            *)    die "software.toml: [$sect] takes key = \"value\" lines, not '$line'" ;;
        esac
    done < "$MANIFEST"
}

sw_attr() { print -r -- "${SW_ATTR[$1.$2.$3]:-}" }

# ── rendering ─────────────────────────────────────────────────────────────

_sw_cask_file() { print -r -- "$TAPDIR/Casks/$1.rb" }

_sw_render_cask() {
    local n=$1 url ver sha app pkg desc home
    url=$(sw_attr download "$n" url)
    ver=$(sw_attr download "$n" version)
    sha=$(sw_attr download "$n" sha256)
    app=$(sw_attr download "$n" app)
    pkg=$(sw_attr download "$n" pkg)
    desc=$(sw_attr download "$n" desc)
    home=$(sw_attr download "$n" homepage)
    [[ -n "$url" ]] || { REASON="[download.$n] has no url"; return 1 }
    [[ -n "$ver" ]] || { REASON="[download.$n] has no version"; return 1 }
    [[ -n "$sha" ]] || { REASON="[download.$n] has no sha256 (use \"no_check\" only when the url is unstable)"; return 1 }
    [[ -n "$app" || -n "$pkg" ]] || { REASON="[download.$n] needs app= or pkg= — what the payload installs"; return 1 }
    {
        print -r -- "# generated by mac sync from software.toml — edit the manifest, not this"
        print -r -- "cask \"$n\" do"
        print -r -- "  version \"$ver\""
        if [[ "$sha" == no_check ]]; then
            print -r -- "  sha256 :no_check"
        else
            print -r -- "  sha256 \"$sha\""
        fi
        print -r -- ""
        print -r -- "  url \"$url\""
        print -r -- "  name \"${$(sw_attr download "$n" name):-$n}\""
        [[ -n "$desc" ]] && print -r -- "  desc \"$desc\""
        print -r -- "  homepage \"${home:-https://example.invalid/}\""
        print -r -- ""
        [[ -n "$app" ]] && print -r -- "  app \"$app\""
        [[ -n "$pkg" ]] && print -r -- "  pkg \"$pkg\""
        print -r -- "end"
    }
}

_sw_render_brewfile() {
    local n
    print -r -- "# generated by mac sync from software.toml — edit the manifest, not this"
    for n in "${SW_TAP[@]}";  do print -r -- "tap \"$n\""; done
    for n in "${SW_BREW[@]}"; do print -r -- "brew \"$n\""; done
    for n in "${SW_CASK[@]}"; do print -r -- "cask \"$n\""; done
    # adopt: an app already sitting in /Applications that is identical to the
    # pin is taken over rather than refused. Without it, anything installed
    # before Homebrew owned it is a permanent error.
    for n in "${SW_DOWNLOAD[@]}"; do print -r -- "cask \"$TAPNAME/$n\", args: { adopt: true }"; done
}

# The generated tree is what Homebrew reads, so it has to exist before any
# bundle command runs.
software_link_tap() {
    local taps dest
    taps="$(brew --repository 2>/dev/null)/Library/Taps" || return 1
    [[ -d "$taps" ]] || { REASON="cannot find Homebrew's tap directory"; return 1 }
    dest="$taps/${TAPNAME%%/*}/homebrew-${TAPNAME#*/}"
    mkdir -p "${dest:h}" "$TAPDIR/Casks"
    if [[ "$(readlink "$dest" 2>/dev/null)" != "$TAPDIR" ]]; then
        rm -rf "$dest"
        ln -sfn "$TAPDIR" "$dest" || { REASON="cannot link $dest"; return 1 }
    fi
    # Homebrew refuses to load casks from a tap it was never told to trust. This
    # one is generated from software.toml, so trusting it is trusting the
    # manifest — idempotent, and it writes only to Homebrew's own trust.json.
    brew trust --tap "$TAPNAME" >/dev/null 2>&1
    return 0
}

# Writing a cache is not a change to the machine, so this runs during check too:
# the only drift worth reporting is a package that is missing, never a derived
# file that is merely out of date.
software_render() {
    local tmp out n
    software_load
    mkdir -p "$TAPDIR/Casks"
    tmp=$(mktemp)
    if ! _sw_render_brewfile > "$tmp"; then rm -f "$tmp"; return 1; fi
    mv -f "$tmp" "$BREWFILE"
    for n in "${SW_DOWNLOAD[@]}"; do
        out=$(_sw_cask_file "$n")
        tmp=$(mktemp)
        if ! _sw_render_cask "$n" > "$tmp"; then rm -f "$tmp"; return 1; fi
        mv -f "$tmp" "$out"
    done
    # A cask whose declaration was deleted must not keep installing itself.
    for out in "$TAPDIR"/Casks/*.rb(N); do
        n="${out:t:r}"
        (( ${SW_DOWNLOAD[(Ie)$n]} )) || rm -f "$out"
    done
    return 0
}
