# One list of software, and Homebrew as the only thing that installs any of it.
#
# software.toml is the whole authoring surface: [install] is a flat list of
# names, [download.NAME] is something Homebrew has no cask for, and [manual.NAME]
# is something no script may install at all. Everything else here is rendering —
# the Brewfile and the casks under tap/ are generated, committed, and are the
# lock: a version bump is a diff you can read rather than a hidden state file.
typeset -g MANIFEST="$ROOT/software.toml"
typeset -g BREWFILE="$ROOT/Brewfile"
typeset -g TAPDIR="$ROOT/tap"
typeset -g TAPNAME="mac-setup/local"

typeset -ga SW_TAP SW_INSTALL SW_DOWNLOAD SW_MANUAL
typeset -gA SW_ATTR SW_VERB
typeset -gi SW_LOADED=0

_sw_trim() {
    setopt localoptions extendedglob
    local s=$1
    s="${s##[[:space:]]##}"
    s="${s%%[[:space:]]##}"
    print -r -- "$s"
}

# A deliberately small subset: section headers, bare names, and key = "value".
# Anything TOML can express that this cannot is a feature the manifest does not
# have, which is the point.
software_load() {
    (( SW_LOADED )) && return 0
    SW_LOADED=1
    SW_TAP=(); SW_INSTALL=(); SW_DOWNLOAD=(); SW_MANUAL=(); SW_ATTR=()
    [[ -f "$MANIFEST" ]] || return 0
    local line sect='' name='' key val
    while IFS= read -r line; do
        line=$(_sw_trim "${line%%$'\r'}")
        [[ -z "$line" || "$line" == '#'* ]] && continue
        if [[ "$line" == '['*']' ]]; then
            sect="${${line#\[}%\]}"
            name=''
            case "$sect" in
                download.*) name="${sect#download.}"; sect=download; SW_DOWNLOAD+=("$name") ;;
                manual.*)   name="${sect#manual.}";   sect=manual;   SW_MANUAL+=("$name") ;;
            esac
            continue
        fi
        if [[ "$line" == *=* && "$sect" == (download|manual) ]]; then
            key=$(_sw_trim "${line%%=*}")
            val=$(_sw_trim "${line#*=}")
            val="${val%\"}"; val="${val#\"}"
            SW_ATTR[$sect.$name.$key]="$val"
            continue
        fi
        # A bare word, in a section that takes bare words.
        line="${line%%[[:space:]]#*}"
        case "$sect" in
            tap)     SW_TAP+=("$line") ;;
            install) SW_INSTALL+=("$line") ;;
            '')      die "software.toml: '$line' is outside any section" ;;
        esac
    done < "$MANIFEST"
    _sw_read_verbs
}

sw_attr() { print -r -- "${SW_ATTR[$1.$2.$3]:-}" }

# Whether a name is a formula or a cask is settled once and written into the
# Brewfile, so the manifest never has to say and a render stays offline.
_sw_read_verbs() {
    SW_VERB=()
    [[ -f "$BREWFILE" ]] || return 0
    local line n
    while IFS= read -r line; do
        case "$line" in
            'brew "'*) n="${${line#brew \"}%\"*}"; SW_VERB[$n]=brew ;;
            'cask "'*) n="${${line#cask \"}%\"*}"; [[ "$n" == */* ]] || SW_VERB[$n]=cask ;;
        esac
    done < "$BREWFILE"
}

_sw_classify() {
    local n=$1
    [[ -n "${SW_VERB[$n]:-}" ]] && { print -r -- "${SW_VERB[$n]}"; return 0 }
    if brew info --formula "$n" >/dev/null 2>&1; then print -r -- brew; return 0; fi
    if brew info --cask "$n" >/dev/null 2>&1; then print -r -- cask; return 0; fi
    return 1
}

# ── rendering ─────────────────────────────────────────────────────────────

_sw_cask_file() { print -r -- "$TAPDIR/Casks/$1.rb" }

_sw_render_cask() {
    local n=$1 url ver sha app pkg desc home
    url=$(sw_attr download "$n" url)
    ver=$(sw_attr download "$n" version)
    sha=$(sw_attr download "$n" sha256)
    app=$(sw_attr download "$n" app)
    pkg=$(sw_attr download "$n" pkg)
    desc=$(sw_attr download "$n" desc)
    home=$(sw_attr download "$n" homepage)
    [[ -n "$url" ]] || { REASON="[download.$n] has no url"; return 1 }
    [[ -n "$ver" ]] || { REASON="[download.$n] has no version"; return 1 }
    [[ -n "$sha" ]] || { REASON="[download.$n] has no sha256 (use \"no_check\" only when the url is unstable)"; return 1 }
    [[ -n "$app" || -n "$pkg" ]] || { REASON="[download.$n] needs app= or pkg= — what the payload installs"; return 1 }
    {
        print -r -- "# generated by mac sync from software.toml — edit the manifest, not this"
        print -r -- "cask \"$n\" do"
        print -r -- "  version \"$ver\""
        if [[ "$sha" == no_check ]]; then
            print -r -- "  sha256 :no_check"
        else
            print -r -- "  sha256 \"$sha\""
        fi
        print -r -- ""
        print -r -- "  url \"$url\""
        print -r -- "  name \"${$(sw_attr download "$n" name):-$n}\""
        [[ -n "$desc" ]] && print -r -- "  desc \"$desc\""
        print -r -- "  homepage \"${home:-https://example.invalid/}\""
        print -r -- ""
        [[ -n "$app" ]] && print -r -- "  app \"$app\""
        [[ -n "$pkg" ]] && print -r -- "  pkg \"$pkg\""
        print -r -- "end"
    }
}

_sw_render_brewfile() {
    local n verb
    print -r -- "# generated by mac sync from software.toml — edit the manifest, not this"
    for n in "${SW_TAP[@]}";  do print -r -- "tap \"$n\""; done
    (( ${#SW_TAP} )) && print -r -- ""
    for n in "${SW_INSTALL[@]}"; do
        verb=$(_sw_classify "$n") || { REASON="'$n' is neither a formula nor a cask — check the spelling, or move it to [download.$n]"; return 1 }
        print -r -- "$verb \"$n\""
    done
    (( ${#SW_DOWNLOAD} )) && print -r -- ""
    # adopt: an app already sitting in /Applications that is byte-identical to
    # the pin is taken over rather than refused. Without it, anything installed
    # before Homebrew owned it is a permanent error.
    for n in "${SW_DOWNLOAD[@]}"; do print -r -- "cask \"$TAPNAME/$n\", args: { adopt: true }"; done
}

# The generated tree is what Homebrew reads, so it has to exist before any
# bundle command runs. A symlink, so the casks Homebrew resolves are the ones
# committed in the repo and there is no copy to fall out of date.
software_link_tap() {
    local taps dest
    taps="$(brew --repository 2>/dev/null)/Library/Taps" || return 1
    [[ -d "$taps" ]] || { REASON="cannot find Homebrew's tap directory"; return 1 }
    dest="$taps/${TAPNAME%%/*}/homebrew-${TAPNAME#*/}"
    mkdir -p "${dest:h}" "$TAPDIR/Casks"
    if [[ "$(readlink "$dest" 2>/dev/null)" != "$TAPDIR" ]]; then
        rm -rf "$dest"
        ln -sfn "$TAPDIR" "$dest" || { REASON="cannot link $dest"; return 1 }
    fi
    # Homebrew refuses to load casks from a tap it was never told to trust. This
    # one is generated by this repo from software.toml, so trusting it is
    # trusting the manifest — idempotent, and it writes only to Homebrew's own
    # trust.json.
    brew trust --tap "$TAPNAME" >/dev/null 2>&1
    return 0
}

# Renders into place and says whether anything actually changed, so a check can
# report a stale Brewfile as drift without writing during a check.
software_render() {
    local mode=${1:-write} tmp out n changed=0
    software_load
    mkdir -p "$TAPDIR/Casks"
    tmp=$(mktemp)
    if ! _sw_render_brewfile > "$tmp"; then rm -f "$tmp"; return 2; fi
    if ! cmp -s "$tmp" "$BREWFILE"; then
        changed=1
        [[ "$mode" == write ]] && mv -f "$tmp" "$BREWFILE"
    fi
    rm -f "$tmp"
    for n in "${SW_DOWNLOAD[@]}"; do
        out=$(_sw_cask_file "$n")
        tmp=$(mktemp)
        if ! _sw_render_cask "$n" > "$tmp"; then rm -f "$tmp"; return 2; fi
        if ! cmp -s "$tmp" "$out"; then
            changed=1
            [[ "$mode" == write ]] && mv -f "$tmp" "$out"
        fi
        rm -f "$tmp"
    done
    # A cask whose declaration was deleted must not keep installing itself.
    for out in "$TAPDIR"/Casks/*.rb(N); do
        n="${out:t:r}"
        (( ${SW_DOWNLOAD[(Ie)$n]} )) && continue
        changed=1
        [[ "$mode" == write ]] && rm -f "$out"
    done
    (( changed )) && return 1
    return 0
}
