# generated by mac sync from software.toml — edit the manifest, not this
cask "hiddify" do
  version "4.1.1"
  sha256 "2019c85aef259002909a088be7bfb28032bf9ce7f932ffa597fdfe3b4cbff914"

  url "https://github.com/hiddify/hiddify-app/releases/download/v4.1.1/Hiddify-MacOS.dmg"
  name "hiddify"
  desc "Proxy client used by the private vpn tree"
  homepage "https://hiddify.com/"

  app "Hiddify.app"
end
